/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 earth-ver2.gltf
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import PropTypes from 'prop-types';

export function Model(props) {
    const group = useRef();
    const { onLoad } = props;
    const { nodes, materials, animations } = useGLTF('/earth-ver2.gltf');
    const { actions, mixer } = useAnimations(animations, group);

    useEffect(() => {
        onLoad();
        group.current.position.set(3, 0, 0);
        group.current.rotation.set(0, 3.8, 0);
        actions['Action'].play();
        actions['Action.001'].play();
        actions['Scene'].play();
        actions['rings_Material.006_0Action'].play();

        return () => {
            mixer.stopAllAction();
        };
    }, [actions, mixer, onLoad]);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
                    <group name="b10b0b2d3f0741fa8ef24abb7586b618fbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="boards" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                                    <mesh
                                        name="boards_Blue_Emission_0"
                                        geometry={nodes.boards_Blue_Emission_0.geometry}
                                        material={materials.Blue_Emission}
                                    />
                                    <mesh
                                        name="boards_metal_0"
                                        geometry={nodes.boards_metal_0.geometry}
                                        material={materials.metal}
                                    />
                                </group>
                                <group
                                    name="earth"
                                    position={[0, 88.768, 0]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                >
                                    <mesh
                                        name="earth_Material001_0"
                                        geometry={nodes.earth_Material001_0.geometry}
                                        material={materials['Material.001']}
                                    />
                                    <mesh name="Grid" geometry={nodes.Grid.geometry} material={materials.LatLong} />
                                </group>
                                <group
                                    name="rings"
                                    position={[0, 88.768, 0]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={172.427}
                                >
                                    <mesh
                                        name="rings_Material006_0"
                                        geometry={nodes.rings_Material006_0.geometry}
                                        material={materials['Material.006']}
                                        scale={0.96}
                                    />
                                </group>
                                <group
                                    name="Camera"
                                    position={[866.735, 607.999, -990.066]}
                                    rotation={[-Math.PI, -0.852, 2.709]}
                                    scale={100}
                                >
                                    <group name="Object_7" />
                                </group>
                                <group
                                    name="holo_room"
                                    position={[0, -66.659, 0]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={[100, 100, 40]}
                                >
                                    <mesh
                                        name="holo_room_Blue_Emission_0"
                                        geometry={nodes.holo_room_Blue_Emission_0.geometry}
                                        material={materials.Blue_Emission}
                                    />
                                    <mesh
                                        name="holo_room_metal2_0"
                                        geometry={nodes.holo_room_metal2_0.geometry}
                                        material={materials.metal2}
                                    />
                                    <mesh
                                        name="holo_room_metal3_0"
                                        geometry={nodes.holo_room_metal3_0.geometry}
                                        material={materials.metal3}
                                    />
                                    <mesh
                                        name="holo_room_metal4_0"
                                        geometry={nodes.holo_room_metal4_0.geometry}
                                        material={materials.metal4}
                                    />
                                    <mesh
                                        name="holo_room_metal_0"
                                        geometry={nodes.holo_room_metal_0.geometry}
                                        material={materials.metal}
                                    />
                                    <mesh
                                        name="holo_room_Orange_Emission_0"
                                        geometry={nodes.holo_room_Orange_Emission_0.geometry}
                                        material={materials.Orange_Emission}
                                    />
                                    <mesh
                                        name="holo_room_Purple_Emission_0"
                                        geometry={nodes.holo_room_Purple_Emission_0.geometry}
                                        material={materials.Purple_Emission}
                                    />
                                    <mesh
                                        name="holo_room_Yellow_Emission_0"
                                        geometry={nodes.holo_room_Yellow_Emission_0.geometry}
                                        material={materials.Yellow_Emission}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
                <group
                    name="Sketchfab_model001"
                    position={[-0.02, 0.01, 0.04]}
                    rotation={[-1.533, 0.03, -1.743]}
                    scale={0.0002}
                >
                    <group name="2f00bbb5de554e94b58444d8d69a8e7bfbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="RootNode001">
                            <group name="polySurface45">
                                <group name="polySurface52" position={[161.242, 644.846, 1396.7]}>
                                    <mesh
                                        name="polySurface52_Main_Body_0"
                                        geometry={nodes.polySurface52_Main_Body_0.geometry}
                                        material={materials.Main_Body}
                                        position={[4857.189, 3908.604, -2406.228]}
                                        rotation={[2, 0.962, -1.729]}
                                    />
                                </group>
                            </group>
                            <group name="polySurface56">
                                <group name="polySurface67" position={[328.696, 644.846, 1396.7]} />
                                <group name="polySurface68" position={[289.933, 644.846, 1396.699]} />
                                <group name="polySurface69" position={[240.275, 644.846, 1396.7]} />
                            </group>
                            <group name="polySurface60">
                                <group name="polySurface70" position={[161.242, 644.846, 1396.7]} />
                                <group name="polySurface71" position={[161.242, 644.846, 1396.7]} />
                                <group name="polySurface73" position={[161.242, 644.846, 1396.7]} />
                                <group name="polySurface74" position={[161.242, 645.692, 2308.162]} />
                            </group>
                            <group
                                name="polySurface63"
                                position={[0, 0, -2396.372]}
                                rotation={[0, 0, Math.PI]}
                                scale={-1}
                            >
                                <group name="polySurface64" position={[328.696, 644.846, -1396.7]} />
                                <group name="polySurface65" position={[289.933, 644.846, -1396.7]} />
                                <group name="polySurface66" position={[240.275, 644.846, -1396.7]} />
                            </group>
                        </group>
                    </group>
                </group>
                <group
                    name="넙스_원형"
                    position={[0, 0.69, 0]}
                    rotation={[-0.291, -0.082, 0.267]}
                    scale={[1, 1, 0.93]}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/earth-ver2.gltf');

Model.propTypes = {
    onLoad: PropTypes.func.isRequired,
};

Model.defaultProps = {
    onLoad: null,
};
